# Generated by Django 4.2.1 on 2023-05-12 15:08

import json
import requests
from urllib.parse import urlparse, urlunparse, urljoin

from bs4 import BeautifulSoup
from django.core.files.base import ContentFile
from django.db import migrations
from tqdm import tqdm


def get_links():
    BASE_URL = "https://github.com/"
    url = "https://github.com/devmanorg/where-to-go-places/tree/master/places"
    response = requests.get(url)
    response.raise_for_status()

    soup = BeautifulSoup(response.content, "html.parser")
    all_links = soup.find_all("a", class_="js-navigation-open")
    links = []

    for link in all_links:
        href = link.get("href")
        if href.endswith(".json"):
            parsed = urlparse(href)
            path = parsed.path
            row_file_path = path.replace("blob", "raw")
            rel = urlunparse(parsed._replace(path=row_file_path))
            href = urljoin(BASE_URL, rel)
            links.append(href)
    return links


print(get_links())