# Generated by Django 4.2.1 on 2023-05-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description_short', models.TextField(blank=True, null=True)),
                ('description_long', models.TextField()),
                ('lon', models.DecimalField(decimal_places=14, max_digits=16, null=True, verbose_name='Longitude')),
                ('lat', models.DecimalField(decimal_places=14, max_digits=16, null=True, verbose_name='Latitude')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('order_num', models.IntegerField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place')),
            ],
        ),
    ]
