# Generated by Django 4.2.1 on 2023-05-07 10:29

from django.db import migrations
import json
import codecs
import requests
from django.core.files.base import ContentFile


def load_data(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    Image = apps.get_model('places', 'Image')
    for file in ['moscow_legends.json', 'roofs24.json']:
        with codecs.open(file, 'r', encoding='utf-8') as f:
            item = json.load(f)

        place = Place.objects.create(
            title=item['title'],
            description_short=item['description_short'],
            description_long=item['description_long'],
            lon=float(item['coordinates']['lng']),
            lat=float(item['coordinates']['lat'])
        )

        for img_url in item['imgs']:
            response = requests.get(img_url)
            img_name = img_url.split('/')[-1]
            image = Image(place=place)
            image.img.save(img_name, ContentFile(response.content), save=True)


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
