# Generated by Django 4.2.1 on 2023-05-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20230507_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order_num']},
        ),
        migrations.AlterField(
            model_name='image',
            name='order_num',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
