# Generated by Django 4.2.1 on 2023-05-12 14:12

from django.db import migrations
from django.contrib.auth.models import User


def generate_superuser(apps, schema_editor):
    User.objects.create_superuser('neko', '', '1234')


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20230507_1347'),
    ]

    operations = [
        migrations.RunPython(generate_superuser),
    ]
