# Generated by Django 4.2.1 on 2023-05-10 15:52

from django.db import migrations
from tinymce.models import HTMLField


def text_to_html(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    for place in Place.objects.all():
        place.description_long_html = place.description_long
        place.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_options_alter_image_order_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='Place',
            name='description_long_html',
            field=HTMLField(blank=True, null=True),
        ),
        migrations.RunPython(text_to_html),

        migrations.RemoveField('Place', 'description_long'),

        migrations.RenameField(
            model_name='Place',
            old_name='description_long_html',
            new_name='description_long'),
    ]
